# Build settings
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-toc

# Site settings
title: "UXDev's Blog"
description: > # this means to ignore newlines until "email:"
   UX개발팀 기술 블로그
email: skypacific@gmail.com
logo: "/assets/images/internet.png"
cover: "/assets/images/background_image.jpg"

name: 'heehun kang'
author: 'heehun kang'
author_image: "/assets/images/kang.heehun.jpg"

paginate:	15

permalink: /:year/:month/:day/:title.html

timezone: "Asia/Seoul"

url: "https://skypacific.github.io" # the base hostname & protocol for your site
baseurl: ""
mailchimp: ""
feedly: ""
twitter_handle: "@skypacific"

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# for thumbnail
absolute_root_path: /Users/heehun.kang/Documents/jekyll/skypacific.github.io

# tracking & ad code
#fb_app_id: "1611862309129685"
#google_analytics_id: "UA-43194822-1"
#google_ad_client: "ca-pub-2468713653725581"
#google_ad_slot_1_id: "1015072194"
#google_ad_slot_2_id: "8649023787"
#naver_site_verification: "cc257cc7988ed85c9db6c228330b4870f9dfa25f"

# social icons and sharing options
social:
#  - icon:	twitter
#    url:	https://twitter.com/skypacific
#    desc: Follow me on twitter
#    share_url: http://twitter.com/share
#    share_title: ?text=
#    share_link: "&amp;url="

# - icon:	facebook
#   url:	https://facebook.com/skypacific
#   desc: Connect with me facebook
#   share_url: https://www.facebook.com/sharer.php
#   share_title: ?t=
#   share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/skypacific
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:

exclude:
  - "*.iml"